# Generated by Django 4.1 on 2022-09-25 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Celular', models.CharField(max_length=11)),
                ('Fecha_Ingreso_Empresa', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Celular', models.CharField(max_length=11)),
                ('Fecha_Ingreso_Empresa', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_Empresa',
            fields=[
                ('ID_Empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('NIT', models.CharField(max_length=10)),
                ('Nombre_Empresa', models.CharField(max_length=30)),
                ('Email_Coorporativo', models.EmailField(max_length=254)),
                ('Telefono_Coorporativo', models.CharField(max_length=11)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinanApp.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('Numero_Cuenta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Fecha_Transaccion', models.DateField()),
                ('Valor_Transaccion', models.IntegerField()),
                ('ID_Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinanApp.perfil_empresa')),
            ],
        ),
    ]
