# Generated by Django 4.1 on 2022-09-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFinanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Documento', models.IntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=30)),
                ('Clave', models.CharField(max_length=30)),
                ('Rol', models.CharField(max_length=30)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFinanApp.administrador')),
            ],
        ),
    ]
